In [10]:
import pandas as pd

# Load the uploaded combined datasets
sp500_data_path = '../data/processed/fill_combined_data_sp500.csv'
nasdaq_data_path = '../data/processed/fill_combined_data_nasdaq.csv'

# Load the datasets to inspect their contents
sp500_data = pd.read_csv(sp500_data_path)
nasdaq_data = pd.read_csv(nasdaq_data_path)

# Display initial info to understand the data structure and missing values
sp500_info = sp500_data.info()
nasdaq_info = nasdaq_data.info()

# Display first few rows to examine the structure
sp500_head = sp500_data.head()
nasdaq_head = nasdaq_data.head()

(sp500_info, sp500_head, nasdaq_info, nasdaq_head)

from sklearn.preprocessing import StandardScaler

# Function to normalize data using StandardScaler
def normalize_data(df, exclude_columns):
    scaler = StandardScaler()
    
    # Separate columns to exclude from scaling (e.g., Date, Market_Label)
    scaled_data = df.copy()
    cols_to_scale = [col for col in df.columns if col not in exclude_columns]
    
    # Apply StandardScaler to numerical columns
    scaled_data[cols_to_scale] = scaler.fit_transform(df[cols_to_scale])
    return scaled_data

# Exclude 'Date' and 'Market_Label' from scaling
exclude_columns = ['Date', 'Market_Label']

# Apply normalization to the datasets
sp500_normalized = normalize_data(sp500_data, exclude_columns)
nasdaq_normalized = normalize_data(nasdaq_data, exclude_columns)

# Save the normalized datasets
sp500_normalized_path = '../data/standardscaler/normalized_combined_data_sp500.csv'
nasdaq_normalized_path = '../data/standardscaler/normalized_combined_data_nasdaq.csv'

sp500_normalized.to_csv(sp500_normalized_path, index=False)
nasdaq_normalized.to_csv(nasdaq_normalized_path, index=False)

sp500_normalized_path, nasdaq_normalized_path

print(sp500_normalized.head())
print(nasdaq_normalized.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8032 entries, 0 to 8031
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               8032 non-null   object
 1   Close              8032 non-null   float64
 2   High               8032 non-null   float64
 3   Low                8032 non-null   float64
 4   Open               8032 non-null   float64
 5   Volume             8032 non-null   int64
 6   Market_Label       8032 non-null   int64
 7   GDP Growth         8032 non-null   float64
 8   CPI                8032 non-null   float64
 9   Interest Rate      8032 non-null   float64
 10  M2 Money Supply    8032 non-null   float64
 11  PPI                8032 non-null   float64
 12  Unemployment Rate  8032 non-null   float64
dtypes: float64(10), int64(2), object(1)
memory usage: 815.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6490 entries, 0 to 6489
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               6490 non-null   object
 1   Close              6490 non-null   float64
 2   High               6490 non-null   float64
 3   Low                6490 non-null   float64
 4   Open               6490 non-null   float64
 5   Volume             6490 non-null   int64
 6   Market_Label       6490 non-null   int64
 7   GDP Growth         6490 non-null   float64
 8   CPI                6490 non-null   float64
 9   Interest Rate      6490 non-null   float64
 10  M2 Money Supply    6490 non-null   float64
 11  PPI                6490 non-null   float64
 12  Unemployment Rate  6490 non-null   float64
dtypes: float64(10), int64(2), object(1)
memory usage: 659.3+ KB
         Date      Close       High        Low       Open   Volume  \
0  1993-01-29  24.526073  24.543517  24.421410  24.543517  1003200
1  1993-02-01  24.700510  24.700510  24.543515  24.543515   480500
2  1993-02-02  24.752853  24.770297  24.630746  24.683078   201300
3  1993-02-03  25.014505  25.031949  24.770291  24.787735   529400
4  1993-02-04  25.119164  25.171495  24.822618  25.101720   531500

   Market_Label  GDP Growth       CPI  Interest Rate  M2 Money Supply  \
0             1   -0.089889  0.429002       1.461424        -1.509059
1             1   -0.089889  0.429002       1.455530        -1.509059
2             1   -0.089889  0.429002       1.502683        -1.509059
3             1   -0.089889  0.429002       1.496788        -1.509059
4             1   -0.089889  0.429002       1.461424        -1.509059

        PPI  Unemployment Rate
0 -0.101701           0.820935
1 -0.101701           0.820935
2 -0.101701           0.820935
3 -0.101701           0.820935
4 -0.101701           0.820935
         Date      Close       High        Low       Open   Volume  \
0  1999-03-10  43.417278  43.496992  42.752999  43.470421  5232000
1  1999-03-11  43.629845  43.988555  42.779568  43.736129  9688600
2  1999-03-12  42.567005  43.496996  42.221580  43.470425  8743600
3  1999-03-15  43.789280  43.842422  42.434151  42.885860  6369000
4  1999-03-16  44.161274  44.347272  43.496995  43.975276  4905800

   Market_Label  GDP Growth       CPI  Interest Rate  M2 Money Supply  \
0             1    0.852295 -0.174761       1.351665        -0.317378
1             1    0.852295 -0.174761       1.359018        -0.317378
2             1    0.852295 -0.174761       1.322254        -0.317378
3             1    0.852295 -0.174761       1.314901        -0.317378
4             1    0.852295 -0.174761       1.285489        -0.317378

        PPI  Unemployment Rate
0 -0.616108          -0.692036
1 -0.616108          -0.692036
2 -0.616108          -0.692036
3 -0.616108          -0.692036
4 -0.616108          -0.692036